### ISSUE TITLE
[Crash] Crash while Rendering Overlay

### ISSUE THREAD

**Issue by WordStormRose** [SuperMartijn642/ConnectedGlass#23] opened 2022-06-05 18:35 UTC
**Version Info**
- Minecraft, 1.18.2 | Forge 40.1.45
- Connected Glass, 1.1.3-mc1.18

**Steps to Reproduce**
Adding the newest version of Connected Glass to a Forge profile higher than 40.1.40 results in a crash with overlay rendering. Tested most recently in 40.1.45, but it also crashes in 40.1.44.

_The game crashed whilst rendering overlay
Error: net.minecraftforge.fml.ModLoadingException: Connected Glass (connectedglass) encountered an error during the done event phase
Exit Code: -1_

**Crash report (~/logs/latest.log)**
[crash-2022-06-05_11.32.02-client.txt](https://github.com/SuperMartijn642/ConnectedGlass/files/8840527/crash-2022-06-05_11.32.02-client.txt)

**Comment by SuperMartijn642** [comment] 2022-06-05 20:17
Seems to be caused by an additional check added in Forge 40.1.43.
Looking at the code now, the way I was doing it before is just stupid. A lot of Connected Glass' code is still from a while ago when I didn't have as much experience with modding 🤦‍♂️

Should be fixed now in Connected Glass 1.1.3a for Minecraft 1.15, 1.16, 1.17, and 1.18.
Thank you for reporting the issue!

**Closed as completed by SuperMartijn642** 2022-06-05 20:17 UTC
Labels: crash
