### ISSUE TITLE
[Bug] Missing texture and I don't know what the cause is.

### ISSUE THREAD

**Issue by toeygame04** [SuperMartijn642/ConnectedGlass#82] opened 2024-10-17 15:54 UTC
**Version Info**
- Minecraft, 1.18.2 (fabric version)
- Connected Glass, 1.1.12 (fabric version)

**Description of the Bug**
I really don't know which mod is incompatible with this mod or made this mod broken. I tried to reinstall all the mod I need but it didn't work. therefore, i want to know what I suppose to do with it. Here is the screenshot and my latest log file. thank you in advance.

**Steps to Reproduce**
...

**Screenshots**
![Screenshot 2024-10-17 222726](https://github.com/user-attachments/assets/2fab6707-c6bf-479c-be4f-8d6813b388b3)
[latest.log](https://github.com/user-attachments/files/17415624/latest.log)

**Comment by SuperMartijn642** [comment] 2024-10-17 16:00
This is caused by ThonkUtil. That mod breaks any resource pack models which are not in a subfolder. It has been reported to them and has been fixed in that mod for newer Minecraft versions, but they have not fixed it for 1.18.2.
I would suggest not using that mod.

**Closed as completed by SuperMartijn642** 2024-10-17 16:00 UTC
Labels: bug

**Comment by toeygame04** [comment] 2024-10-17 16:05
thank you so much for replying me very fast 🙇🏻‍♀️🙇🏻‍♀️
