### ISSUE TITLE
[Bug] Glass textures do not connect

### ISSUE THREAD

**Issue by zezreli** [SuperMartijn642/ConnectedGlass#21] opened 2022-02-06 15:21 UTC
**Version Info**
- Minecraft, 1.18.1
- Connected Glass, 1.1.1-mc1.18

**Description of the Bug**
only parts of the connected glass are actually connecting, what i mean is that, if i place two or more connected glass next to each other they dont connect but if i look through them they are connected, so they still look like seperate blocks unless you look through them. 

**Steps to Reproduce**
i do not actually know, 
so i just downloaded it, ive used the mods in previous minecraft versions but only now it is not working

**Screenshots**
![2022-02-06_16 20 04](https://user-images.githubusercontent.com/27296782/152687810-6b9c0d60-cb1a-4a29-a4db-86d00dc411a7.png)
![2022-02-06_16 19 57](https://user-images.githubusercontent.com/27296782/152687813-a05c6d60-9f64-44f1-ab15-32db24a52d37.png)
![2022-02-06_16 19 58](https://user-images.githubusercontent.com/27296782/152687816-b13368c4-916b-4f02-96f4-6035a24303c4.png)
![2022-02-06_16 20 03](https://user-images.githubusercontent.com/27296782/152687818-ff77e81e-9b44-40ae-bed4-a1ecdf1a4573.png)

**Comment by SuperMartijn642** [comment] 2022-02-07 08:56
It seems to work fine for me.

Does this issue happen when you are using only Connected Glass? If not, what other mods are you using?

**Comment by zezreli** [comment] 2022-02-07 11:14
ill check, but i have around 280 mods installed total

**Comment by zezreli** [comment] 2022-02-07 11:19
![2022-02-07_12 18 43](https://user-images.githubusercontent.com/27296782/152778543-439da12a-c8a4-4912-b9f9-965ea2be70b7.png)
without any other mods installed it works just fine. do you want me to send you a list of the mods installed?

**Comment by SuperMartijn642** [comment] 2022-02-07 22:05
Could you narrow it down to fewer mods?

If not, the mod list would be nice. Maybe some mod sticks out to me. Downloading that many mods one by one from CurseForge is just too much effort for me.

**Comment by zezreli** [comment] 2022-02-07 22:12
ill compose a list of the mods and if you see any mods that sticks out let me know, ill do a test of removing a few mods and see if it still causes an issue, ill do a few testest tomorrow aswell as compose a list, lets figure this out

**Comment by SuperMartijn642** [comment] 2022-04-19 21:25
This is likely caused by Magnesium if you had that installed. They fixed the issue in a new version.

Anyways, closing this as they're hasn't been a reply.

**Closed as completed by SuperMartijn642** 2022-04-19 21:25 UTC
Labels: bug
